packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1055.0'
  - '@aws-sdk/lib-storage@3.1055.0'
  - '@aws-sdk/s3-request-presigner@3.1055.0'
