export enum ApiErrorCode {
  VALIDATION_FAILED = "VALIDATION_FAILED",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  NOTEBOOK_NOT_FOUND = "NOTEBOOK_NOT_FOUND",
  PRESENTATION_NOT_FOUND = "PRESENTATION_NOT_FOUND",
  SLIDE_NOT_FOUND = "SLIDE_NOT_FOUND",
  ASSET_NOT_FOUND = "ASSET_NOT_FOUND",
  THEME_NOT_FOUND = "THEME_NOT_FOUND",
  EXPORT_JOB_NOT_FOUND = "EXPORT_JOB_NOT_FOUND",
  SHARE_LINK_NOT_FOUND = "SHARE_LINK_NOT_FOUND",
}
