import type { z } from "zod";
import { PresentationDocumentSchema } from "../presentation-model/document.schema.js";

/**
 * Schema for a PresentationDocument generated by the backend (planner).
 * Strict validation: no unknown keys allowed.
 * This is the contract for the planner output before persistence.
 */
export const BackendPresentationDocumentSchema = PresentationDocumentSchema.strict();

export type BackendPresentationDocument = z.infer<typeof BackendPresentationDocumentSchema>;
